version: 1.0.{build}
image: Visual Studio 2019
skip_tags: true
skip_branch_with_pr: true
skip_commits:
  files:
    - .github/*
    - '**/*.md'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(appveyor_build_version)'
  package_version: '$(appveyor_build_version)'
  assembly_version: '$(appveyor_build_version)'
  file_version: '$(appveyor_build_version)'
  informational_version: '$(appveyor_build_version)'
build_script:
- cmd: >-
    dotnet pack src\What3Passwords.sln --configuration Release
test: off
artifacts:
- path: src\nupkg\What3Passwords.$(appveyor_build_version).nupkg
  name: What3Passwords.$(appveyor_build_version).nupkg
deploy:
- provider: NuGet
  api_key: $(blythmeister_nuget_key)
  artifact: What3Passwords.$(appveyor_build_version).nupkg
  on:
    branch: master
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: v$(appveyor_build_version)
  description: Release v$(appveyor_build_version)
  auth_token: $(blythmeister_github_key)
  repository: BlythMeister/What3Passwords
  artifact: What3Passwords.$(appveyor_build_version).nupkg
  on:
    branch: master

